[package]
name = "kybernet"
version = "0.9.0"
description = "PID 1 init system for AGNOS"
license = "GPL-3.0-only"
language = "cyrius"

[build]
entry = "src/main.cyr"
test = "src/test.cyr"
output = "kybernet"

[deps]
stdlib = ["string", "fmt", "alloc", "io", "vec", "str", "fnptr", "tagged", "callback", "assert", "bench"]

[deps.agnosys]
git = "https://github.com/MacCracken/agnosys"
tag = "0.90.0"
modules = ["lib/syscalls_linux.cyr"]

[deps.agnostik]
git = "https://github.com/MacCracken/agnostik"
tag = "0.95.0"
modules = ["src/security.cyr", "src/agent.cyr", "src/error.cyr"]
