#!/usr/bin/env bash
# mkcred.sh — generate an emergency-shell credential for
# /etc/kybernet/config.json.
#
# Until 1.5.9 the credential was an unsalted SHA-256 digest and provisioning it
# was `printf 'pw' | sha256sum`. That is no longer true, and there was no other
# way to produce one — which is precisely why this script exists: a credential
# format with no generator is a format nobody can adopt.
#
# Usage:
#   ./scripts/mkcred.sh                      # prompt for the password
#   ./scripts/mkcred.sh --check '<record>'   # verify a record's shape
#   T=3 M=32768 ./scripts/mkcred.sh          # override the cost parameters
#
# Output is one line, the value for "emergency_password_hash":
#   v1$<t>$<m>$<p>$<salt-hex>$<tag-hex>
#
# WHY OPENSSL AND NOT A COMPILED TOOL
# -----------------------------------
# kybernet is PID 1 and has no command line — `main()` takes no arguments and
# `args` is not even a pinned dependency. Adding an argv-parsing path to the
# one process that must never crash, so that it can also be a password utility,
# is a bad trade. OpenSSL 3.2+ implements RFC 9106 Argon2id, and its output was
# verified byte-for-byte identical to sigil's — the implementation kybernet
# actually verifies with — at m=19456/t=2/p=1:
#
#   sigil   8c194cb37afbddc6888ab9984059bc26f05fdc9f19c3fd3a201f83590f80d428
#   openssl 8c194cb37afbddc6888ab9984059bc26f05fdc9f19c3fd3a201f83590f80d428
#
# That equality is not taken on faith either: src/test.cyr's
# test_emergency_cred_verify() carries two records generated by this exact
# openssl invocation and asserts kybernet verifies them, so the generator and
# the verifier are checked against each other on every test run.

set -euo pipefail

# RFC 9106's memory-constrained option, as OWASP states it. The same triple
# Rust's Argon2::default() emits, and what sy-core and agnostic use — the AGNOS
# pack has one answer here, not four.
#
# ⚠ These must stay inside the bounds src/lib/emergency_auth.cyr enforces, and
# the checks below are a copy of them. kybernet REJECTS an out-of-range record
# at config-load time rather than clamping it — clamping a verification
# parameter would derive a different tag and turn a typo into a permanent
# lockout — so a record this script emits outside the bounds is a credential
# nobody can use.
#
#   1 <= T <= 8            8192 <= M <= 65536 KiB          P == 1
#   M * T <= 131072        16 <= salt <= 64 B              32 <= tag <= 64 B
#
# The floors are deliberately above sigil's: sigil accepts M >= 8*P (8 KiB),
# an 8-byte salt and a 4-byte tag, none of which is a security floor.
#
# ⚠ THE CEILINGS ON SALT AND TAG MATTER AS MUCH AS THE FLOORS. They were
# minimums only until they were caught by review: `TAG_BYTES=128` produced a
# record this script emitted, self-checked and blessed, and which kybernet
# then classified INVALID and dropped — leaving an operator who picked a
# LONGER tag "for safety" with no emergency shell and no diagnostic. A
# generator whose output its own consumer refuses is the 1.5.4-1.5.7 brick
# class, reached through the tool the release ships to prevent it.
T="${T:-2}"
M="${M:-19456}"
P="${P:-1}"
SALT_BYTES="${SALT_BYTES:-16}"
TAG_BYTES="${TAG_BYTES:-32}"

T_MAX=8; M_MIN=8192; M_MAX=65536; WORK_MAX=131072
SALT_MIN_HEX=32; SALT_MAX_HEX=128; TAG_MIN_HEX=64; TAG_MAX_HEX=128
# The prompt buffer in src/main.cyr is 512 bytes and _read_line_fd refuses an
# overflow rather than truncating, so a password past this length could be
# provisioned and then never typed in.
PW_MAX=256

die() { echo "mkcred: $*" >&2; exit 1; }

# --- record shape check (also used by the qemu fixture builder) -------------
if [ "${1:-}" = "--check" ]; then
    rec="${2:?Usage: mkcred.sh --check '<record>'}"
    case "$rec" in
        'v1$'*) ;;
        *) die "not a v1 record: $rec" ;;
    esac
    # ⚠ COUNT THE SEPARATORS BEFORE SPLITTING. With `IFS=$`, `read`'s last
    # variable absorbs the remainder, and a record with a single TRAILING `$`
    # leaves `extra` UNSET — so a `[ -n "$extra" ]` test passes it, while
    # kybernet's `_emerg_field(h, 6)` returns a non-null zero-length field and
    # rejects the record as malformed. The script would bless a credential the
    # board refuses. An exact separator count has no such blind spot.
    seps="${rec//[^$]/}"
    [ "${#seps}" -eq 5 ] || die "record has ${#seps} separators, expected exactly 5"
    case "$rec" in *'$') die "record ends with a separator (empty seventh field)" ;; esac

    IFS='$' read -r v ct cm cp csalt ctag extra <<< "$rec"
    if [ -n "${extra:-}" ]; then die "record has a seventh field"; fi
    [ "$v" = "v1" ] || die "bad version field: $v"
    for f in "$ct" "$cm" "$cp"; do
        case "$f" in ''|*[!0-9]*) die "non-numeric cost field: $f" ;; esac
        # ⚠ LENGTH, CHECKED BEFORE THE `10#` NORMALISATION. 1.6.16 LOW-4.
        #
        # kybernet's `_emerg_parse_bounded` bounds DURING decimal accumulation
        # and gives up past 19 digits, so a longer cost field is classified
        # INVALID — but this checker normalised through `$((10#$f))` first,
        # which happily collapses 25 zero-padded digits to a small in-range
        # number and then blessed the record. `--check` said OK and kybernet
        # rejected it: exactly the "a generator whose output its own consumer
        # refuses" class this script's own header warns about, and with
        # `emergency_require_auth: true` it is a board that prompts for a
        # password nothing can match.
        #
        # Phrased as a LENGTH rule, not a leading-zero rule: the 64-bit wrap
        # variant of this has no leading zeros at all. Generation can never emit
        # it (it normalises first), so this is a --check-only divergence.
        [ "${#f}" -le 19 ] || die "cost field is ${#f} digits; kybernet's parser gives up past 19"
    done
    # ⚠ EVERY ARITHMETIC EXPANSION BELOW USES 10#. bash's $(( )) honours a
    # base prefix, so $((08192)) is "value too great for base 8" — a FATAL
    # expansion error. And `set -e` does not stop the script on it, because
    # the failure is inside a `[ ... ] || die` list: both the test and the die
    # argument fail to expand, neither command runs, and execution simply
    # continues. Before this fix, `--check 'v1$2$08192$1$...'` skipped the
    # remaining validation and fell through into KEY GENERATION, printing a
    # brand-new unrelated credential and exiting 0. kybernet's own
    # _emerg_parse_bounded is strict base-10 and accepts 08192 happily, so
    # this was a valid record the checker structurally could not check.
    ct=$((10#$ct)); cm=$((10#$cm)); cp=$((10#$cp))
    for f in "$csalt" "$ctag"; do
        case "$f" in ''|*[!0-9a-fA-F]*) die "non-hex field: $f" ;; esac
        [ $(( ${#f} % 2 )) -eq 0 ] || die "odd-length hex field: $f"
    done
    [ "${#csalt}" -ge "$SALT_MIN_HEX" ] || die "salt is $(( ${#csalt} / 2 )) bytes; RFC 9106 §4 wants 16"
    [ "${#csalt}" -le "$SALT_MAX_HEX" ] || die "salt is $(( ${#csalt} / 2 )) bytes; kybernet caps it at 64"
    [ "${#ctag}" -ge "$TAG_MIN_HEX" ] || die "tag is $(( ${#ctag} / 2 )) bytes; RFC 9106 §4 wants 32"
    [ "${#ctag}" -le "$TAG_MAX_HEX" ] || die "tag is $(( ${#ctag} / 2 )) bytes; kybernet caps it at 64"
    [ "$ct" -ge 1 ] && [ "$ct" -le "$T_MAX" ] || die "t_cost $ct outside 1..$T_MAX"
    [ "$cm" -ge "$M_MIN" ] && [ "$cm" -le "$M_MAX" ] || die "m_cost $cm outside $M_MIN..$M_MAX KiB"
    [ "$cp" -eq 1 ] || die "parallelism must be 1 (sigil's fill is serial; p>1 helps only the attacker)"
    [ $(( cm * ct )) -le "$WORK_MAX" ] || die "m_cost x t_cost = $(( cm * ct )) exceeds the work cap $WORK_MAX"
    echo "OK: v1 record, argon2id t=$ct m=${cm}KiB p=$cp salt=$(( ${#csalt} / 2 ))B tag=$(( ${#ctag} / 2 ))B work=$(( cm * ct ))"
    exit 0
fi

# --- parameter bounds FIRST, toolchain second --------------------------------
#
# ⚠ ORDER MATTERS, and getting it wrong made a CI check fake. The openssl
# ARGON2ID probe used to run here, before the bounds — so on a runner with
# OpenSSL 3.0 (Ubuntu 24.04) EVERY invocation died on the probe, including the
# five deliberately-out-of-range ones ci.yml asserts are refused. All five
# exited non-zero for the wrong reason, the check saw five refusals, and it
# printed success while testing nothing. On a dev box with OpenSSL 3.6 the
# same five refused correctly, so the divergence was invisible locally.
#
# Validating parameters needs no crypto. Do it first, always, everywhere.

# Same base-prefix hazard as `--check`: `T=08` would make every `$(( ))` below
# a fatal "value too great for base", and `set -e` does not stop a failing
# command inside a `[ … ] || die` list. Normalise first, once.
case "$T$M$P$SALT_BYTES$TAG_BYTES" in *[!0-9]*) die "T/M/P/SALT_BYTES/TAG_BYTES must be decimal integers" ;; esac
T=$((10#$T)); M=$((10#$M)); P=$((10#$P))
SALT_BYTES=$((10#$SALT_BYTES)); TAG_BYTES=$((10#$TAG_BYTES))

[ "$T" -ge 1 ] && [ "$T" -le "$T_MAX" ] || die "T=$T outside kybernet's accepted 1..$T_MAX"
[ "$M" -ge "$M_MIN" ] && [ "$M" -le "$M_MAX" ] || die "M=$M outside kybernet's accepted $M_MIN..$M_MAX (KiB)"
[ "$P" -eq 1 ] || die "P must be 1 — sigil fills lanes serially, so p>1 costs the defender nothing and saves the attacker a factor of p"
[ $(( M * T )) -le "$WORK_MAX" ] || die "M x T = $(( M * T )) exceeds the work cap $WORK_MAX (this bounds the PID-1 stall at phase 6c)"
[ "$SALT_BYTES" -ge 16 ] || die "SALT_BYTES=$SALT_BYTES below RFC 9106 §4's 16"
[ "$SALT_BYTES" -le 64 ] || die "SALT_BYTES=$SALT_BYTES above kybernet's 64 — the record would be REJECTED at boot"
[ "$TAG_BYTES" -ge 32 ] || die "TAG_BYTES=$TAG_BYTES below RFC 9106 §4's 32"
[ "$TAG_BYTES" -le 64 ] || die "TAG_BYTES=$TAG_BYTES above kybernet's 64 — the record would be REJECTED at boot"

# Only now does anything need openssl. Note the harness does NOT come through
# here — qemu/mkcred-fixture.cyr mints the gate's credential with sigil's own
# Argon2id, precisely so a release gate never depends on a host capability.
command -v openssl >/dev/null 2>&1 || die "openssl not found (need 3.2+ for ARGON2ID)"
openssl list -kdf-algorithms 2>/dev/null | grep -qi ARGON2ID \
    || die "this openssl has no ARGON2ID KDF — need OpenSSL 3.2 or newer ($(openssl version))"

# --- password ----------------------------------------------------------------
# Read from a tty with echo off. Taking it as an argv value instead would put
# the plaintext in the process table and the shell history of whatever machine
# provisions the board.
if [ -n "${KYB_PASSWORD:-}" ]; then
    # Non-interactive escape hatch for CI and the qemu fixture builder. Note it
    # is an ENVIRONMENT variable, not an argument, for the reason above.
    pw="$KYB_PASSWORD"
else
    [ -t 0 ] || die "no tty for the prompt; set KYB_PASSWORD for non-interactive use"
    # ⚠ `IFS=` IS LOAD-BEARING. With the default IFS, `read` strips leading and
    # trailing whitespace — but kybernet's `_read_line_fd` copies raw bytes up
    # to the first CR/LF and strips nothing. A passphrase with an edge space
    # would be hashed trimmed and typed untrimmed, so the tags differ, the
    # authentication fails, and a failed authentication halts PID 1 forever.
    # `Confirm:` cannot catch it either — both reads trim identically. The
    # pre-1.5.9 recipe (`printf 'pw' | sha256sum`) had no trim, so this would
    # have been a regression introduced by the provisioning tool itself.
    IFS= read -rsp 'Password: ' pw; echo >&2
    IFS= read -rsp 'Confirm:  ' pw2; echo >&2
    [ "$pw" = "$pw2" ] || die "passwords do not match"
fi
[ -n "$pw" ] || die "empty password"

# ⚠ THE PASSWORD DOMINATES EVERYTHING THE KDF DOES. At the default parameters
# an offline attacker manages on the order of 1e4 guesses/second against this
# credential — which is years against a random passphrase and about five
# minutes against anything in a 10-million-entry wordlist. Choosing Argon2id
# over SHA-256 moves the line from "instant" to "years" ONLY for a password
# that is not already on a list. `hunter2` is not.
if [ "${#pw}" -lt 12 ]; then
    if [ "${ALLOW_WEAK:-0}" != "1" ]; then
        die "password is ${#pw} characters; use 12+ (a multi-word passphrase is best), or set ALLOW_WEAK=1"
    fi
    echo "mkcred: WARNING — ${#pw}-character password accepted via ALLOW_WEAK=1." >&2
    echo "mkcred: a memory-hard KDF does not rescue a password that is on a wordlist." >&2
fi

# ⚠ A CEILING TOO. kybernet reads the prompt into a 512-byte buffer and
# `_read_line_fd` REFUSES an overflow rather than truncating — so a password
# past this length could be provisioned here and then never entered on the
# console. Minting a credential nobody can type is the same brick as minting
# one nobody can parse.
if [ "${#pw}" -gt "$PW_MAX" ]; then
    die "password is ${#pw} bytes; kybernet's console prompt accepts at most $PW_MAX"
fi

# --- salt --------------------------------------------------------------------
# A fresh CSPRNG salt per credential. This is the entire point of the format
# change: without it one rainbow table covers every AGNOS board at once.
salt=$(openssl rand -hex "$SALT_BYTES")
[ "${#salt}" -eq $(( SALT_BYTES * 2 )) ] || die "salt generation failed"

# --- derive ------------------------------------------------------------------
# openssl's `iter` is Argon2's t_cost, `memcost` its m_cost in KiB, `lanes` its
# parallelism. The password goes through -kdfopt rather than a file, so it is
# visible in this process's own argv for the life of one openssl invocation —
# acceptable on a provisioning workstation, and the reason this script is not
# meant to run on a shared host.
tag=$(openssl kdf -keylen "$TAG_BYTES" \
        -kdfopt "pass:$pw" \
        -kdfopt "hexsalt:$salt" \
        -kdfopt "iter:$T" \
        -kdfopt "memcost:$M" \
        -kdfopt "lanes:$P" \
        -binary ARGON2ID | od -An -tx1 -v | tr -d ' \n')
[ "${#tag}" -eq $(( TAG_BYTES * 2 )) ] || die "kdf produced ${#tag} hex chars, expected $(( TAG_BYTES * 2 ))"

record="v1\$$T\$$M\$$P\$$salt\$$tag"

# Self-check before handing it over: the generator must never emit a record its
# own validator rejects.
"$0" --check "$record" >/dev/null || die "generated a record that fails validation"

echo "$record"

cat >&2 <<EOF

Put this in /etc/kybernet/config.json:

  "emergency_require_auth": true,
  "emergency_password_hash": "$record"

kybernet logs the parameters (never the salt or tag) at boot, so a typo shows
up in dmesg long before the night the emergency shell is needed.
EOF
