#!/usr/bin/env bash
# verify-lock.sh — prove the COMMITTED cyrius.lock is what cyrius.cyml
# actually resolves to.
#
# ⚠ WHY THIS EXISTS: `cyrius deps --verify` CANNOT CATCH A STALE COMMITTED
# LOCK, because CI resolves first. The `Resolve dependencies` step runs
# `cyrius deps`, which REWRITES cyrius.lock from disk; the next step then runs
# `cyrius deps --verify` against the file it just wrote. That is tautological —
# it verifies the resolve against itself and reports "N verified, 0 failed" no
# matter what was committed.
#
# This is not hypothetical and it is not a hazard of one feature. kybernet
# 1.6.12 was first committed with cyrius.cyml at argonaut tag = "1.13.8" and a
# cyrius.lock still pinning 1.13.7's commit (7204b60), because the tag did not
# exist yet at commit time. Run against that exact tree, `cyrius deps` silently
# rewrote 7204b60 -> 8e98429 in place and verify still said "70 verified, 0
# failed". CI would have gone green. It took a second commit to correct.
#
# CLAUDE.md documents this shape for `path` overrides ("the lock is written
# from disk, so deps --verify can't catch it") — but it is a property of the
# STEP ORDER and applies to every release.
#
# TWO HALVES, both required:
#
#   1. OFFLINE (no network). Every git dep declared in cyrius.cyml must have a
#      `commit` line in the lock, and that line's TAG FIELD must equal the
#      manifest's tag. This alone catches the 1.6.12 case in milliseconds, and
#      it is also the only automated check of the `path`-override hazard —
#      a `path =` override makes git/tag inert AND DROPS that dep's commit line
#      from the lock entirely, so `deps --verify` cannot miss what is not there
#      (kybernet 1.5.4 shipped with no argonaut commit pin for exactly this).
#
#   2. RESOLVE (authoritative). Save the committed lock, resolve, compare,
#      restore. Catches a lock carrying the right tag with a wrong commit —
#      a moved tag, a hand-edit, or a hash line that drifted.
#
# ⚠ A NAIVE `diff` IS A FALSE POSITIVE AND MUST NOT BE SHIPPED. `cyrius deps`
# does not emit the lock's hash lines in a stable ORDER, so a byte diff reports
# drift on a perfectly correct lock. Compare SORTED. Verified to pass on the
# correct lock (twice, for ordering stability), fail on the stale one, and not
# false-positive.
#
# ⚠ THIS GATE IS NON-MUTATING, like `cyrius fmt --check`. Half 2 has to run a
# real resolve, which rewrites cyrius.lock — so the committed bytes are
# restored on EVERY exit path. A gate that reformats the tree underneath the
# steps that follow it is standing rule 11's mistake wearing a different hat.
#
# Usage:
#   bash scripts/verify-lock.sh          # both halves (release gate / CI)
#
# There is deliberately NO skip flag. If the resolve cannot run, this FAILS
# with the reason — a missing prerequisite must never pass quietly (rule 32),
# and a skip must never look like a pass (rule 33).

set -euo pipefail

cd "$(dirname "$0")/.."

MANIFEST="cyrius.cyml"
LOCK="cyrius.lock"

[ -f "$MANIFEST" ] || { echo "ERROR: no $MANIFEST here"; exit 1; }

if [ ! -f "$LOCK" ]; then
    echo "ERROR: $LOCK is missing."
    echo "  The lock is the dependency contract — lib/ is gitignored, so the"
    echo "  bytes on disk are not it. Run 'cyrius deps' and commit the result."
    exit 1
fi

fail=0

# ---------------------------------------------------------------------------
# ⚠ WHICH BYTES ARE WE VERIFYING? HEAD'S, NOT THE WORKING TREE'S. 1.6.19.
# ---------------------------------------------------------------------------
# This gate shipped at 1.6.13 reading the WORKING TREE lock, and that reproduced
# the very tautology it was written to break, one level up. `cyrius build` and
# `cyrius deps` both REWRITE cyrius.lock from disk as a side effect. Every
# release gate list runs a build before this script, so by the time it ran, the
# working-tree lock had already been regenerated by the same resolver it was
# about to be compared against — and half 2 could not fail. Half 1 was no better
# off: a build that rewrites a stale pin CORRECTS it in the working tree, so the
# offline check passed while the committed file was still wrong. That is
# precisely the 1.6.12 case in the header above, which this script exists for.
#
# The question the gate must answer is "if CI checks out THIS COMMIT and
# resolves, does it get this lock?" — and that is a question about HEAD's bytes.
# A dirty working tree is a separate, and separately reported, condition: it is
# normal mid-release (the lock is committed alongside the bump), so it is a
# NOTICE, not a failure. What is never acceptable is the two being conflated.
#
# ⚠ The restore path must still put back the WORKING TREE bytes, not HEAD's —
# restoring HEAD would make this "non-mutating" gate silently discard a lock
# change the operator was about to commit.
LOCK_TMP=$(mktemp -d)
COMMITTED="$LOCK_TMP/head.lock"
WORKTREE="$LOCK_TMP/worktree.lock"
cp "$LOCK" "$WORKTREE"

cleanup_lock_tmp() { rm -rf "$LOCK_TMP"; }
trap cleanup_lock_tmp EXIT

LOCK_SOURCE="working tree"
LOCK_DIRTY=0
if git rev-parse --git-dir > /dev/null 2>&1 && git cat-file -e "HEAD:$LOCK" 2> /dev/null; then
    git show "HEAD:$LOCK" > "$COMMITTED"
    LOCK_SOURCE="HEAD"
    cmp -s "$COMMITTED" "$WORKTREE" || LOCK_DIRTY=1
else
    # Not a git repo, or the lock is untracked. Fall back, but SAY SO — a gate
    # that quietly checks something weaker than it claims is a log line
    # (standing rule 32), and an untracked lock is itself worth shouting about.
    cp "$WORKTREE" "$COMMITTED"
    echo "NOTICE: $LOCK is not tracked at HEAD (or this is not a git checkout)."
    echo "        Falling back to the working-tree copy, which CANNOT catch a"
    echo "        stale committed lock. Commit $LOCK to get the real check."
    echo
fi

if [ "$LOCK_DIRTY" -eq 1 ]; then
    echo "NOTICE: $LOCK has uncommitted changes; verifying HEAD's copy, which is"
    echo "        what CI will check out. If the resolve below matches your"
    echo "        working tree but not HEAD, the fix is to COMMIT $LOCK."
    echo
fi

# ---------------------------------------------------------------------------
# Half 1 — offline: manifest tags vs lock commit lines.
# ---------------------------------------------------------------------------
# A lock commit line is TAB-separated:
#   commit <sha> <name> <url> <tag>
# Field 5 is the tag the commit was resolved FROM, which is exactly the field
# that goes stale when cyrius.cyml is bumped and the lock is not re-resolved.

echo "=== half 1: manifest tags vs lock pins at $LOCK_SOURCE (offline) ==="

# Enumerate the git deps declared in the manifest. `[deps]` (the stdlib list)
# has no `git =` line and is correctly excluded. A section whose `git` was
# neutered by a `path` override still declares git+tag here, which is the
# point: the lock must still carry the pin.
DECLARED=$(awk '
    /^\[/ {
        if (name != "" && git != "") print name "\t" tag
        name = ""; git = ""; tag = ""
        if ($0 ~ /^\[deps\./) { n = $0; sub(/^\[deps\./, "", n); sub(/\].*$/, "", n); name = n }
        next
    }
    /^[[:space:]]*git[[:space:]]*=/  { git = $0 }
    /^[[:space:]]*path[[:space:]]*=/ { path = $0 }
    /^[[:space:]]*tag[[:space:]]*=/  { t = $0; sub(/^[^"]*"/, "", t); sub(/".*$/, "", t); tag = t }
    END { if (name != "" && git != "") print name "\t" tag }
' "$MANIFEST")

if [ -z "$DECLARED" ]; then
    echo "ERROR: parsed ZERO git deps out of $MANIFEST."
    echo "  kybernet has four (sigil, agnostik, libro, argonaut). Zero means the"
    echo "  manifest shape changed and this gate can no longer read it — which"
    echo "  is a gate that cannot fail, not a manifest with no deps."
    echo "  (cyrius <= 6.5.27 also read only the first 4095 bytes of a manifest"
    echo "  and resolved a section past that window to zero deps, silently.)"
    exit 1
fi

NDECL=$(printf '%s\n' "$DECLARED" | wc -l)
echo "manifest declares $NDECL git dep(s)"

while IFS=$'\t' read -r name mtag; do
    [ -n "$name" ] || continue
    # Field 3 is the dep name; anchor on it so `sigil` cannot match a
    # hypothetical `sigil_tpm` line.
    ltag=$(awk -F'\t' -v n="$name" '$1 == "commit" && $3 == n { print $5; found = 1 }
                                    END { if (!found) print "" }' "$COMMITTED")
    lsha=$(awk -F'\t' -v n="$name" '$1 == "commit" && $3 == n { print $2 }' "$COMMITTED")
    if [ -z "$lsha" ]; then
        echo "  FAIL: $name — declared git+tag in $MANIFEST, but NO commit line in $LOCK."
        echo "        This is the 'path override' shape: git/tag go inert and the"
        echo "        commit pin is dropped, and 'deps --verify' reports success"
        echo "        because it cannot miss what is not there. kybernet 1.5.4"
        echo "        shipped with no argonaut pin for exactly this reason."
        fail=1
        continue
    fi
    if [ "$ltag" != "$mtag" ]; then
        echo "  FAIL: $name — $MANIFEST says tag '$mtag', $LOCK pins tag '$ltag' ($lsha)."
        echo "        The lock is STALE. Re-resolve and commit the result:"
        echo "          rm -rf lib && cyrius deps && cyrius deps --verify"
        fail=1
        continue
    fi
    echo "  OK: $name $mtag -> $lsha"
done <<< "$DECLARED"

if [ "$fail" -ne 0 ]; then
    echo
    echo "ERROR: the committed lock does not agree with the manifest."
    exit 1
fi

# ---------------------------------------------------------------------------
# Half 2 — resolve and compare. Authoritative; needs network.
# ---------------------------------------------------------------------------
echo
echo "=== half 2: resolve and compare against the lock at $LOCK_SOURCE ==="

TMPDIR_GATE=$(mktemp -d)
SAVED="$COMMITTED"
RESOLVED="$TMPDIR_GATE/resolved.lock"
DEPSLOG="$TMPDIR_GATE/deps.log"

# ⚠ RESTORE ON EVERY EXIT PATH, including the failure ones. Half 2 rewrites
# cyrius.lock as a side effect of resolving; leaving the rewrite in place would
# make this gate silently "fix" the very drift it exists to report, and would
# hand the next CI step a file the commit never contained.
restore_lock() {
    # ⚠ WORKTREE, not SAVED. SAVED is HEAD's copy; restoring it here would throw
    # away an uncommitted lock change the operator is mid-way through making.
    if [ -f "$WORKTREE" ]; then cp "$WORKTREE" "$LOCK"; fi
    rm -rf "$TMPDIR_GATE"
    cleanup_lock_tmp
}
trap restore_lock EXIT

if ! cyrius deps > "$DEPSLOG" 2>&1; then
    echo "  FAIL: 'cyrius deps' did not succeed, so there is nothing to compare"
    echo "        against — and a gate is not satisfied by a resolve that did not"
    echo "        happen. The resolver's own error follows."
    echo
    echo "        One expected cause is a lock pinning a DIFFERENT sha for the"
    echo "        SAME tag: cyrius refuses that itself, as a force-pushed or"
    echo "        repointed tag. Note it does NOT refuse a lock pinning a"
    echo "        different TAG — that is silently re-pinned, which is exactly"
    echo "        the 1.6.12 case and is what half 1 above is for."
    echo
    tail -20 "$DEPSLOG" || true
    exit 1
fi

cp "$LOCK" "$RESOLVED"

# ⚠ SORTED. `cyrius deps` does not emit the hash lines in a stable order, so an
# unsorted diff reports drift on a correct lock — a false positive that would
# get this gate disabled within a release.
if diff -q <(sort "$SAVED") <(sort "$RESOLVED") > /dev/null 2>&1; then
    NLINES=$(wc -l < "$SAVED" | tr -d ' ')
    echo "  OK: the lock at $LOCK_SOURCE is byte-identical (sorted) to a fresh resolve"
    echo "      ($NLINES lines, $NDECL commit pins)"
else
    echo "  FAIL: a fresh resolve does not match the $LOCK_SOURCE copy of $LOCK."
    echo
    # Two very different causes, one message each — telling them apart is the
    # difference between "run git add" and "your manifest or toolchain drifted".
    # ⚠ A DIFF CONFINED TO `lib/*.cyr` HASH LINES IS A TOOLCHAIN DIFF, NOT A
    # DEP DIFF, and the two want opposite responses. `cyrius deps` writes a
    # hash for every stdlib file it lands, so a locally MODIFIED ~/.cyrius/lib
    # — an in-flight compiler fix, a patched stdlib — moves those hashes while
    # every `commit` pin stays put. Committing that lock reds CI, because CI
    # installs the pinned cyrius release and reproduces the ORIGINAL hashes.
    # Distinguishing this from a real dep change is the difference between
    # "commit the lock" and "do not commit the lock".
    PIN_DELTA=$(diff <(sort "$SAVED") <(sort "$RESOLVED") 2>/dev/null | grep -cE '^[<>].*(^|[[:space:]])commit[[:space:]]' || true)
    if [ "${PIN_DELTA:-0}" -eq 0 ]; then
        echo "  ⚠ Every commit pin is IDENTICAL — the difference is only in stdlib"
        echo "    file hashes. That is a TOOLCHAIN difference, not a dependency"
        echo "    one: your ~/.cyrius/lib has been modified relative to the"
        echo "    cyrius release pinned in $MANIFEST. CI installs the pinned"
        echo "    release and will reproduce HEAD's hashes, so the committed lock"
        echo "    is the correct one. ⚠ Do NOT commit the regenerated lock — it"
        echo "    would red CI. Files that differ:"
        diff <(sort "$SAVED") <(sort "$RESOLVED") 2>/dev/null | grep -oE 'lib/[A-Za-z0-9_]+\.cyr' | sort -u | sed 's/^/      /' | head -20 || true
        echo
    elif [ "$LOCK_DIRTY" -eq 1 ] && diff -q <(sort "$WORKTREE") <(sort "$RESOLVED") > /dev/null 2>&1; then
        echo "  ⚠ The resolve MATCHES your working tree and differs only from HEAD."
        echo "    Your lock is correct but UNCOMMITTED. Commit $LOCK — CI checks"
        echo "    out HEAD and will resolve against the stale copy otherwise."
        echo
    fi
    echo "  '<' = only in the $LOCK_SOURCE lock   '>' = only in the FRESH resolve"
    diff <(sort "$SAVED") <(sort "$RESOLVED") | head -40 || true
    echo
    echo "  The committed lock is stale. 'cyrius deps --verify' cannot report"
    echo "  this: CI resolves BEFORE it verifies, so it checks the resolve"
    echo "  against the file the resolve just wrote."
    echo
    echo "  Fix: rm -rf lib && cyrius deps && cyrius deps --verify, then commit"
    echo "       $LOCK in the same commit as $MANIFEST."
    exit 1
fi

echo
echo "lock verified: manifest tags match, and a fresh resolve reproduces the commit"
